% function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
 X1 = SANRE_only.eventLengthVSmax(:,1);
 Y1 = SANRE_only.eventLengthVSmax(:,2);
 X2 = aS_raw.eventLengthVSmax(:,1);
 Y2 = aS_raw.eventLengthVSmax(:,2);

%  Auto-generated by MATLAB on 16-May-2019 15:19:33

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','aS','MarkerSize',10,'Marker','.',...
    'LineStyle','none');

% Create plot
plot(X2,Y2,'DisplayName','SANRE only','MarkerSize',10,'Marker','.',...
    'LineStyle','none');

% Create ylabel
ylabel('Max Intensity (au)');

% Create xlabel
xlabel('Event Length');

% Create title
title({'Total Length of Event vs. Max Instensity of Event'});

box(axes1,'on');
% Create legend
legend(axes1,'show');

